2017-12-12 16:20:02 Error: [Cake\Routing\Exception\MissingControllerException] Controller class CakePHP could not be found.
Exception Attributes: array (
  'class' => 'CakePHP',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-12 16:24:55 Error: [Cake\Controller\Exception\MissingActionException] Action CakePHPController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CakePHPController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-12 16:25:48 Error: [Cake\View\Exception\MissingTemplateException] Template file "CakePHP\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'CakePHP\\index.ctp',
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('CakePHP\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-13 12:47:50 Error: [Cake\Routing\Exception\MissingControllerException] Controller class T could not be found.
Exception Attributes: array (
  'class' => 'T',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /t
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-13 13:24:57 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:24:58 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:26:30 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:26:34 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:29:08 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:29:08 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:34:26 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:34:27 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:34:30 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:34:30 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:38:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:38:14 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:38:17 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 13:38:17 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 13:57:52 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Champ 'Prestataires.slug' inconnu dans where clause
Request URL: /prestataires/view
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\PrestatairesController->view()
#12 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#15 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 14:09:09 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Champ 'Prestataires.slug' inconnu dans where clause
Request URL: /prestataires/view/1
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\PrestatairesController->view('1')
#12 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#15 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 14:14:57 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:14:57 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:15:07 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:15:07 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:16:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:16:14 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:16:19 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:16:19 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:16:50 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:16:50 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:17:08 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:17:08 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:17:38 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:17:39 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:18:08 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:18:08 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:18:10 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 14:18:10 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /workout/cakephp/prestataires
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 14:39:56 Error: [BadMethodCallException] Method getData does not exist
Request URL: /prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 14:44:30 Error: [BadMethodCallException] Method getData does not exist
Request URL: /prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 14:53:50 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Champ 'Prestataires.slug' inconnu dans where clause
Request URL: /prestataires/view
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\PrestatairesController->view()
#12 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#15 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 15:01:23 Error: [BadMethodCallException] Method getData does not exist
Request URL: /workout/cakephp/prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:04:37 Error: [BadMethodCallException] Method getData does not exist
Request URL: /workout/cakephp/prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:04:43 Error: [BadMethodCallException] Method getData does not exist
Request URL: /workout/cakephp/prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:24:04 Warning: Warning (2): Missing argument 1 for App\Controller\PrestatairesController::edit() in [C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php, line 38]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\PrestatairesController::edit() - APP/Controller\PrestatairesController.php, line 38
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-13 15:24:04 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 15:24:04 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires/edit
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 15:25:54 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "prestataires"
Request URL: /prestataires/view
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\PrestatairesController->view()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:26:48 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "prestataires"
Request URL: /prestataires/view
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\PrestatairesController->view()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:27:06 Warning: Warning (2): Missing argument 1 for App\Controller\PrestatairesController::edit() in [C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php, line 38]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\PrestatairesController::edit() - APP/Controller\PrestatairesController.php, line 38
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-13 15:27:06 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 15:27:07 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires/edit
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 15:27:23 Error: [BadMethodCallException] Method getData does not exist
Request URL: /prestataires/add
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php(26): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\PrestatairesController->add()
#2 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PrestatairesController))
#5 C:\wamp64\www\workout\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:27:35 Warning: Warning (2): Missing argument 1 for App\Controller\PrestatairesController::edit() in [C:\wamp64\www\workout\cakephp\src\Controller\PrestatairesController.php, line 38]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\PrestatairesController::edit() - APP/Controller\PrestatairesController.php, line 38
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-13 15:27:35 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 15:27:36 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /prestataires/edit
Stack Trace:
#0 C:\wamp64\www\workout\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\w...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


